import express from 'express';
import {getPost, getPosts, createPost, updatePost, deletePost} from '../controllers/postsController.js';
import {authMiddleware} from '../middleware/auth.js';
const router = express.Router();
router.get('/', getPosts);
router.post('/', authMiddleware, createPost);
router.get('/:id', getPost);
router.put('/:id', authMiddleware, updatePost);
router.delete('/:id', authMiddleware, deletePost);
export default router;